# Generated by Django 5.1.1 on 2024-10-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0012_remove_usuario_categoria_usuario_usuario_carrera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clase',
            new_name='categoria',
        ),
    ]
