# Generated by Django 5.1.1 on 2024-11-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0016_solicitudeliminaciontema_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='anonimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tema',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
