# Generated by Django 5.1.1 on 2024-09-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_categoria_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='descripcion',
            new_name='contenido',
        ),
    ]
