# Generated by Django 5.1.1 on 2024-10-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_comentario_parent_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comentario',
            name='si',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tema',
            name='si',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
