# Generated by Django 5.1.1 on 2024-11-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0015_alter_usuario_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudeliminaciontema',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
